baseURL = "https://xmr2usdt.netlify.app/"
languageCode = "en-us"
title = "Monero Exchange Guides"
theme = "PaperMod"

# Enable features
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true

# Build settings
buildDrafts = false
buildFuture = false
buildExpired = false

# Output formats
[outputs]
home = ["HTML", "RSS", "JSON"]

# Menu
[[menu.main]]
identifier = "exchanges"
name = "Exchanges"
url = "/exchanges/"
weight = 10

[[menu.main]]
identifier = "guides"
name = "Guides"
url = "/guides/"
weight = 20

# Theme settings
[params]
env = "production"
title = "Monero Exchange Guides"
description = "Comprehensive guides for exchanging Monero (XMR) to various cryptocurrencies and fiat currencies"
keywords = ["monero", "xmr", "exchange", "cryptocurrency", "guide"]
author = "Monero Community"
images = ["<link-to-image>"]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

# Schema settings
[params.schema]
type = "Organization"
name = "Monero Exchange Guides"
url = "https://xmr2usdt.netlify.app/"
logo = "/images/logo.png"
description = "Comprehensive guides for exchanging Monero (XMR) to various cryptocurrencies and fiat currencies"

[params.homeInfoParams]
Title = "Welcome to Monero Exchange Guides"
Content = "Your trusted resource for Monero exchange information"

[[params.socialIcons]]
name = "github"
url = "https://github.com/vvmspace"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/vvmspace"

[params.analytics.google]
SiteVerificationTag = "xyz"

[params.profileMode]
enabled = false

[params.taxonomy]
enabled = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]
