baseURL = "https://xmr2usdt.com/"
languageCode = "en-us"
title = "XMR to USDT Exchange Guide"
theme = "PaperMod"

# Enable features
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true

# Build settings
buildDrafts = false
buildFuture = false
buildExpired = false

# Output formats
[outputs]
home = ["HTML", "RSS", "JSON"]

# Menu
[[menu.main]]
identifier = "exchanges"
name = "Exchanges"
url = "/exchanges/"
weight = 10

[[menu.main]]
identifier = "guides"
name = "Guides"
url = "/guides/"
weight = 20

# Theme settings
[params]
env = "production"
title = "XMR to USDT Exchange Guide"
description = "The most comprehensive guide for exchanging Monero (XMR) to USDT and other cryptocurrencies"
keywords = [
    "xmr to usdt",
    "monero to usdt",
    "xmr usdt",
    "monero usdt",
    "exchange xmr to usdt",
    "convert xmr to usdt",
    "xmr2usdt",
    "monero exchange",
    "cryptocurrency exchange",
    "usdt exchange",
]
author = "Monero Community"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

# Schema settings
[params.schema]
type = "Organization"
name = "XMR to USDT Exchange Guide"
url = "https://xmr2usdt.com/"
logo = "/images/logo.png"
description = "The most comprehensive guide for exchanging Monero (XMR) to USDT and other cryptocurrencies"

[params.homeInfoParams]
Title = "XMR to USDT Exchange Guide"
Content = "Your trusted resource for exchanging Monero to USDT and other cryptocurrencies"

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]
