baseURL = "https://xmr2usdt.com/"
languageCode = "en-us"
title = "XMR to USDT Exchange Guide"
theme = "PaperMod"

# Enable features
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true

# Security headers
[security]
[security.headers]
Content-Security-Policy = '''
default-src 'self';
script-src 'self' 'unsafe-inline' 'unsafe-eval' https://changenow.io;
style-src 'self' 'unsafe-inline';
img-src 'self' data: https://changenow.io;
frame-src 'self' https://changenow.io;
connect-src 'self' https://changenow.io;
'''

# Build settings
buildDrafts = false
buildFuture = false
buildExpired = false

# Output formats
[outputs]
home = ["HTML", "RSS", "JSON"]

# Menu
[[menu.main]]
identifier = "exchanges"
name = "Exchanges"
url = "/exchanges/"
weight = 1

[[menu.main]]
identifier = "guides"
name = "Guides"
url = "/guides/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

# Theme settings
[params]
env = "production"
title = "XMR to USDT Exchange Guide"
description = "The most comprehensive guide for exchanging Monero (XMR) to USDT and other cryptocurrencies"
keywords = [
    "xmr to usdt",
    "monero to usdt",
    "xmr usdt",
    "monero usdt",
    "exchange xmr to usdt",
    "convert xmr to usdt",
    "xmr2usdt",
    "monero exchange",
    "cryptocurrency exchange",
    "usdt exchange",
]
author = "XMR to USDT Exchange Guide"
copyright = "© 2025 XMR to USDT Exchange Guide"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

# Schema settings
[params.schema]
type = "Organization"
name = "XMR to USDT Exchange Guide"
url = "https://xmr2usdt.com/"
logo = "/images/logo.png"
description = "The most comprehensive guide for exchanging Monero (XMR) to USDT and other cryptocurrencies"

[params.homeInfoParams]
Title = "XMR to USDT Exchange Guide"
Content = "Your trusted resource for exchanging Monero to USDT and other cryptocurrencies"

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 100
threshold = 0.4
useExtendedSearch = false
ignoreLocation = false
ignoreFieldNorm = false
